Importação da biblioteca numpy

In [34]:
import numpy as np
a = np.array([0,1,2,3,4,5])

In [35]:
a

array([0, 1, 2, 3, 4, 5])

Verifica quantas dimensões existem no array

In [36]:
a.ndim

1

In [37]:
a.shape

(6,)

In [38]:
b = a.reshape((3,2))

In [39]:
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [40]:
b.ndim

2

In [41]:
b[1][0] = 77

In [42]:
b

array([[ 0,  1],
       [77,  3],
       [ 4,  5]])

In [43]:
a

array([ 0,  1, 77,  3,  4,  5])

In [44]:
c = a.reshape(3,2).copy()

In [45]:
c

array([[ 0,  1],
       [77,  3],
       [ 4,  5]])

In [46]:
c [1][0] = 99


In [47]:
print(a)
print("Teste")
print(c)

[ 0  1 77  3  4  5]
Teste
[[ 0  1]
 [99  3]
 [ 4  5]]


In [48]:
a

array([ 0,  1, 77,  3,  4,  5])

In [49]:
a*2

array([  0,   2, 154,   6,   8,  10])

In [50]:
a**2

array([   0,    1, 5929,    9,   16,   25])